addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"             % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.4.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-site" % "1.4.1")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "0.14.5")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.8.0")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"       % "1.8.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages"         % "0.6.3")
