version: '3'
services:
  neo4j:
    image: neo4j:4.3.6
    container_name: neo4j-plume-benchmark
    environment:
      NEO4J_AUTH: "neo4j/neo4j123"
    ports:
      - "7687:7687"
      - "7474:7474"
    healthcheck:
      test: perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - 'neo4j-data:/data'
    stdin_open: true
    tty: true

volumes:
  neo4j-data:
