site:
  about:
    siteName: Plume
    siteDescription: Plume is a language front-end to construct an intermediate
    representation called a code-property graphs from JVM bytecode. Plume is
    graph database agnosic and can store code property graphs to multiple graph databases.
Editorial:
  primaryColor: '#00bdd6'
  legacySearch: false
  metaComponents:
    - type: 'orchidSearch'
  social:
    github: 'plume-oss/plume'
  menu:
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'

kotlindoc:
  sourceDirs:
    - './../../main/kotlin'

services:
  publications:
    stages:
      - type: 'githubPages'
        username: 'DavidBakerEffendi' # the username which created the personal access token
        repo: 'plume-oss/plume' # the repo to publish to
        versioned: true