// Last updated 8/9/2020
graph = JanusGraphFactory.open('/etc/opt/janusgraph/janusgraph.properties')

mgmt = graph.openManagement()
// Vertex labels
mgmt.containsVertexLabel('META_DATA') ?: mgmt.makeVertexLabel('META_DATA').make()
mgmt.containsVertexLabel('FILE') ?: mgmt.makeVertexLabel('FILE').make()
mgmt.containsVertexLabel('METHOD') ?: mgmt.makeVertexLabel('METHOD').make()
mgmt.containsVertexLabel('METHOD_PARAMETER_IN') ?: mgmt.makeVertexLabel('METHOD_PARAMETER_IN').make()
mgmt.containsVertexLabel('METHOD_RETURN') ?: mgmt.makeVertexLabel('METHOD_RETURN').make()
mgmt.containsVertexLabel('MODIFIER') ?: mgmt.makeVertexLabel('MODIFIER').make()
mgmt.containsVertexLabel('TYPE') ?: mgmt.makeVertexLabel('TYPE').make()
mgmt.containsVertexLabel('TYPE_DECL') ?: mgmt.makeVertexLabel('TYPE_DECL').make()
mgmt.containsVertexLabel('BINDING') ?: mgmt.makeVertexLabel('BINDING').make()
mgmt.containsVertexLabel('TYPE_PARAMETER') ?: mgmt.makeVertexLabel('TYPE_PARAMETER').make()
mgmt.containsVertexLabel('TYPE_ARGUMENT') ?: mgmt.makeVertexLabel('TYPE_ARGUMENT').make()
mgmt.containsVertexLabel('MEMBER') ?: mgmt.makeVertexLabel('MEMBER').make()
mgmt.containsVertexLabel('NAMESPACE_BLOCK') ?: mgmt.makeVertexLabel('NAMESPACE_BLOCK').make()
mgmt.containsVertexLabel('LITERAL') ?: mgmt.makeVertexLabel('LITERAL').make()
mgmt.containsVertexLabel('CALL') ?: mgmt.makeVertexLabel('CALL').make()
mgmt.containsVertexLabel('LOCAL') ?: mgmt.makeVertexLabel('LOCAL').make()
mgmt.containsVertexLabel('IDENTIFIER') ?: mgmt.makeVertexLabel('IDENTIFIER').make()
mgmt.containsVertexLabel('FIELD_IDENTIFIER') ?: mgmt.makeVertexLabel('FIELD_IDENTIFIER').make()
mgmt.containsVertexLabel('RETURN') ?: mgmt.makeVertexLabel('RETURN').make()
mgmt.containsVertexLabel('BLOCK') ?: mgmt.makeVertexLabel('BLOCK').make()
mgmt.containsVertexLabel('ARRAY_INITIALIZER') ?: mgmt.makeVertexLabel('ARRAY_INITIALIZER').make()
mgmt.containsVertexLabel('METHOD_REF') ?: mgmt.makeVertexLabel('METHOD_REF').make()
mgmt.containsVertexLabel('JUMP_TARGET') ?: mgmt.makeVertexLabel('JUMP_TARGET').make()
mgmt.containsVertexLabel('TYPE_REF') ?: mgmt.makeVertexLabel('TYPE_REF').make()
mgmt.containsVertexLabel('CONTROL_STRUCTURE') ?: mgmt.makeVertexLabel('CONTROL_STRUCTURE').make()
mgmt.containsVertexLabel('UNKNOWN') ?: mgmt.makeVertexLabel('UNKNOWN').make()
// Edge labels
mgmt.containsEdgeLabel('AST') ?: mgmt.makeEdgeLabel('AST').make()
mgmt.containsEdgeLabel('CFG') ?: mgmt.makeEdgeLabel('CFG').make()
mgmt.containsEdgeLabel('CONTAINS_NODE') ?: mgmt.makeEdgeLabel('CONTAINS_NODE').make()
mgmt.containsEdgeLabel('CAPTURED_BY') ?: mgmt.makeEdgeLabel('CAPTURED_BY').make()
mgmt.containsEdgeLabel('REF') ?: mgmt.makeEdgeLabel('REF').make()
mgmt.containsEdgeLabel('BINDS_TO') ?: mgmt.makeEdgeLabel('BINDS_TO').make()
// Properties
mgmt.containsPropertyKey('AST_PARENT_TYPE') ?: mgmt.makePropertyKey('AST_PARENT_TYPE').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('AST_PARENT_FULL_NAME') ?: mgmt.makePropertyKey('AST_PARENT_FULL_NAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('IS_EXTERNAL') ?: mgmt.makePropertyKey('IS_EXTERNAL').dataType(Boolean.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('FILENAME') ?: mgmt.makePropertyKey('FILENAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('SIGNATURE') ?: mgmt.makePropertyKey('SIGNATURE').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('EVALUATION_STRATEGY') ?: mgmt.makePropertyKey('EVALUATION_STRATEGY').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('NAME') ?: mgmt.makePropertyKey('NAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('VERSION') ?: mgmt.makePropertyKey('VERSION').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('LANGUAGE') ?: mgmt.makePropertyKey('LANGUAGE').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('METHOD_INST_FULL_NAME') ?: mgmt.makePropertyKey('METHOD_INST_FULL_NAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('ARGUMENT_INDEX') ?: mgmt.makePropertyKey('ARGUMENT_INDEX').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('LINE_NUMBER') ?: mgmt.makePropertyKey('LINE_NUMBER').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('COLUMN_NUMBER') ?: mgmt.makePropertyKey('COLUMN_NUMBER').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('FULL_NAME') ?: mgmt.makePropertyKey('FULL_NAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('ORDER') ?: mgmt.makePropertyKey('ORDER').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('CANONICAL_NAME') ?: mgmt.makePropertyKey('CANONICAL_NAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('DISPATCH_TYPE') ?: mgmt.makePropertyKey('DISPATCH_TYPE').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('CODE') ?: mgmt.makePropertyKey('CODE').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('TYPE_FULL_NAME') ?: mgmt.makePropertyKey('TYPE_FULL_NAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('MODIFIER_TYPE') ?: mgmt.makePropertyKey('MODIFIER_TYPE').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('DYNAMIC_TYPE_FULL_NAME') ?: mgmt.makePropertyKey('DYNAMIC_TYPE_FULL_NAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('DYNAMIC_TYPE_HINT_FULL_NAME') ?: mgmt.makePropertyKey('DYNAMIC_TYPE_HINT_FULL_NAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('METHOD_FULL_NAME') ?: mgmt.makePropertyKey('METHOD_FULL_NAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('TYPE_DECL_FULL_NAME') ?: mgmt.makePropertyKey('TYPE_DECL_FULL_NAME').dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.containsPropertyKey('HASH') ?: mgmt.makePropertyKey('HASH').dataType(String.class).cardinality(Cardinality.SINGLE).make()
// Indexes
mgmt.getGraphIndex("byASTOrder") != null ?: mgmt.buildIndex("byASTOrder", Vertex.class).addKey(mgmt.getPropertyKey("ORDER")).buildCompositeIndex()
mgmt.getGraphIndex("byName") != null ?: mgmt.buildIndex("byName", Vertex.class).addKey(mgmt.getPropertyKey("NAME")).buildCompositeIndex()
mgmt.getGraphIndex("byFullName") != null ?: mgmt.buildIndex("byFullName", Vertex.class).addKey(mgmt.getPropertyKey("FULL_NAME")).buildCompositeIndex()
mgmt.getGraphIndex("bySignature") != null ?: mgmt.buildIndex("bySignature", Vertex.class).addKey(mgmt.getPropertyKey("SIGNATURE")).buildCompositeIndex()
mgmt.getGraphIndex("byHash") != null ?: mgmt.buildIndex("byHash", Vertex.class).addKey(mgmt.getPropertyKey("HASH")).buildCompositeIndex()

mgmt.commit()