name: Documentation

on:
  push:
    tags: [ 'd*' ] # Temporarily disable this job

jobs:
  publish:
    name: Publish Scala doc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup SSH Keys and known_hosts
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build code
        run: sbt stage
      - name: Build ScalaDoc website
        run: sbt makeSite
      - name: Deploy ScalaSite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sbt ghpagesPushSite
