name: Release

on:
  push:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  publish:
    name: KDocs with Orchid
    needs: prepare

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build code
    - run: ./gradlew build
    - name: Build and deploy Orchid token
      run: ./gradlew :orchidDeploy -PorchidEnvironment=prod